version: '2'
services:
  rsync-server:
    restart: always
    image: commanderhu/rsync-server
    container_name: rsync-server
    volumes:
      - /var/lib/docker/volumes/zeppelin_notebook/_data:/data/zeppelin_conf # Путь слева указывает путь, для которого необходимо создать резервную копию
      # - /data:/data/ # Путь слева указывает путь, для которого необходимо создать резервную копию
    ports:
      - "874:873"
    environment:
      RSYNC_IP: 10.10.250.146 # Локальный адрес
      RSYNC_PORT: 874 # Отображение порта
      REMOTE_HOST_IP: 10.10.250.145 # ip клиента
      REMOTE_HOST_PORT: 22023 # Порт клиента
