version: '2'
services:
  rsync-server:
    restart: always
    image: commanderhu/rsync-server
    container_name: rsync-server
    volumes:
      - /data:/data/ # Путь слева указывает путь, для которого необходимо создать резервную копию
    ports:
      - "874:873"
    environment:
      RSYNC_IP: flink.tk-1.ru # Локальный адрес
      RSYNC_PORT: 874 # Отображение порта
      REMOTE_HOST_IP: clickhouse.tk-1.ru # ip клиента
      REMOTE_HOST_PORT: 22023 # Порт клиента
